name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Python (robô web)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install -U pip
      - run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: |
          python - <<'PY'
print("✅ Python rodando no CI")
PY

      # Node (robô WhatsApp)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          if [ -f package.json ]; then npm ci || true; fi
      - run: node -e "console.log('✅ Node rodando no CI')"
