name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Primeira conexão (aceitar host key)
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_HOST }} "echo 'SSH OK'"

      - name: Sync código (rsync)
        run: |
          rsync -avz --delete \
            --exclude ".git" \
            --exclude "node_modules" \
            --exclude ".venv" \
            ./ ${{ secrets.SSH_HOST }}:/opt/coletor-precos/

      - name: Instalar deps e reiniciar serviços (PM2)
        run: |
          ssh ${{ secrets.SSH_HOST }} <<'SSH'
          set -e
          cd /opt/coletor-precos

          # Python
          if command -v python3 >/dev/null 2>&1; then
            python3 -m venv .venv || true
            . .venv/bin/activate
            [ -f requirements.txt ] && pip install -U pip && pip install -r requirements.txt || true
            deactivate
          fi

          # Node
          if [ -f package.json ]; then
            if command -v npm >/dev/null 2>&1; then npm ci || npm install; fi
          fi

          # PM2
          if ! command -v pm2 >/dev/null 2>&1; then
            npm i -g pm2
          fi

          # Start/Restart dos processos (ajuste os caminhos conforme seu projeto)
          # Python robot (exemplo)
          if [ -f vibra_marques/main.py ]; then
            . .venv/bin/activate
            pm2 describe robo_web >/dev/null 2>&1 && pm2 restart robo_web || pm2 start python --name robo_web -- vibra_marques/main.py
            deactivate
          fi

          # Node robot (exemplo)
          if [ -f src/index.js ]; then
            pm2 describe robo_whats >/dev/null 2>&1 && pm2 restart robo_whats || pm2 start src/index.js --name robo_whats
          fi

          pm2 save
          SSH
